title: Jordan's Portfolio
baseurl: ""
url: "https://yourusername.github.io"
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
collections:
  projects:
    output: true
    permalink: /projects/:title/
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: compressed
include:
  - _projects
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
